### PR TITLE
set usePolicyFile to true for cross domain swf #4

### PR DESCRIPTION
**Pull request by liufengyun**
@glaszig This commit fix the cross domain issue for me. #4

### CODE REVIEW

**Comment by liufengyun** [comment]
Wait, there still seems to be problem. My staging server works, but production server fails.

**Comment by liufengyun** [comment]
@glaszig I confirm it works now both for my staging and production server. That it didn't work for my production server before is due to some caching problem(the cross domain flash player not updated).

**Comment by glaszig** [comment]
from [the docs](http://www.schillmania.com/projects/soundmanager2/doc/#smsound-usepolicyfile) i'm under the impression that this should work even with this setting being `false` unless you're using id3 stuff.
was the problem related to id3 data in your remote files?

**Comment by liufengyun** [comment]
@glaszig Maybe several issues are mixed together. I'll remove the field, and try if it works.

**Comment by liufengyun** [comment]
@glaszig I confirm that after removing `usePolicyFile: true`, it still works well. Sorry for the misleading information above. I'm closing this pull request.

**Comment by glaszig** [comment]
don't worry. security-related things can be confusing.
however, thank you for taking the pains of testing this!
i will release a new gem later (within the next 10 hours).

**Pull request closed without merging**
