### PR TITLE
Upgrade SoundManager

### PR DESCRIPTION
**Pull request by dkubb**
This Upgrades SoundManager JS and SWF files to the latest stable version.

### CODE REVIEW

**Comment by glaszig** [comment]
thanks!
gem should be available now.

**Comment by casoetan** [comment]
A new version is out and I really need some of its features. Please upgrade. Thanks

**Comment by glaszig** [comment]
@casoetan [0.1.5](https://rubygems.org/gems/soundmanager-rails/versions/0.1.5) is out.
please, try it out and create a new issue if any problem arises. thanks.

**Comment by casoetan** [comment]
Thanks works fine. 
Cheers

**Pull request closed without merging**
